package cl.dsy1103.order.model;

import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// create table menu (
// id number
// generated by default as identity
// primary key,
// name varchar(255) unique not null,
// created_at timestamp default current_timestamp
// );

// create table menu_cost (
// id number
// generated by default as identity
// primary key,
// cost float not null,
// menu_id number unique not null,
// foreign key ( menu_id )
// references menu ( id )
// );

// create table client (
// id number
// generated by default as identity
// primary key,
// name varchar(255) not null,
// rut int unique check ( rut between 0 and 987654321 ),
// phone varchar(20) check ( substr(
// phone,
// 1,
// 3
// ) = '+56' ),
// email varchar(255) check ( email like '%@%' )
// );

// create table client_order (
// id number
// generated by default as identity
// primary key,
// menu_id number not null,
// client_id number,
// foreign key ( menu_id )
// references menu ( id ),
// foreign key ( client_id )
// references client ( id )
// );

@Entity
@Table(name = "menu")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Menu {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(name = "name", unique = true, nullable = false)
    private String name;

    // @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

}
